"""
Django settings for prestamos project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
from dotenv import load_dotenv
import os
from pathlib import Path

load_dotenv(dotenv_path=os.path.join(os.path.dirname(__file__), '..', '.env'))

# Build paths inside the project like this: BASE_DIR / 'subdir' .

# Before docker
#BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/
# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

HOST = os.getenv('APP_RUN_HOST')
DOMAIN = os.getenv('APP_RUN_DOMAIN')

ALLOWED_HOSTS = ["127.0.0.1", "localhost", HOST, DOMAIN]
print(f'HOSTS: {ALLOWED_HOSTS}')

# Application definition

INSTALLED_APPS = [
    # para el admin
    'admin_interface',
    #'extra_settings',
    'colorfield',
    'django.contrib.admin',
    'import_export',

    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    'PEMA.apps.PemaConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware'
]

ROOT_URLCONF = 'prestamos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'prestamos.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DATABASE_NAME'),
        'USER': 'root', # Dejar a puerto root
        'PASSWORD': os.getenv('DATABASE_PASSWORD'),
        'HOST': 'db', # Dejar a db (el nombre del servicio del docker-compose es el host)
        'PORT': '3306' # Dejar a puerto 3306,
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Login
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = '/menu'
LOGOUT_REDIRECT_URL = '/login'

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'es-mx'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / STATIC_URL


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = os.getenv('EMAIL')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_PASSWORD')
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

# Archivos subidos desde django
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / MEDIA_URL

# admin personalizado
X_FRAME_OPTIONS = "SAMEORIGIN"
SILENCED_SYSTEM_CHECKS = ["security.W019"]

# para enviar las urls en los emails
URL_BASE_PARA_EMAILS = "http://", "127.0.0.1"
#URL_BASE_PARA_EMAILS = "http://192.168.1.93:8080" # "http://10.32.213.157" #"http://localhost:8000/"

# django extra settings
# EXTRA_SETTINGS_ADMIN_APP = "extra_settings"
# EXTRA_SETTINGS_CACHE_NAME = "extra_settings"
# EXTRA_SETTINGS_VERBOSE_NAME = "Configuraciones"

# EXTRA_SETTINGS_DEFAULTS = [
#    {
#        "name": "SETTING_NAME3",
#        "type": "time",
#        "value": time(hour=9, minute=0, second=0),
#    },
#]
