# Generated by Django 5.0 on 2024-03-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PEMA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='estado_atr',
            field=models.CharField(choices=[('PN', 'PENDIENTE'), ('RE', 'RECHAZADA'), ('AP', 'APROBADA')], default='PN', max_length=3),
        ),
    ]
