# Generated by Django 5.0.3 on 2024-04-08 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PEMA', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corresponsableorden',
            name='aceptado',
        ),
        migrations.AddField(
            model_name='corresponsableorden',
            name='estado',
            field=models.CharField(choices=[('PN', 'PENDIENTE'), ('RE', 'RECHAZADA'), ('AC', 'ACEPTADA')], default='PN', max_length=2),
        ),
        migrations.AddField(
            model_name='orden',
            name='nombre',
            field=models.TextField(blank=True, max_length=125),
        ),
        migrations.AddField(
            model_name='orden',
            name='tipo',
            field=models.CharField(choices=[('OR', 'ORDINARIA'), ('EX', 'EXTRAORDINARIA')], default='OR', max_length=2),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='PEMA.materia'),
        ),
        migrations.AlterField(
            model_name='corresponsableorden',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PEMA.orden'),
        ),
        migrations.AlterField(
            model_name='corresponsableorden',
            name='prestatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PEMA.prestatario'),
        ),
        migrations.CreateModel(
            name='MaestroMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PEMA.maestro')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PEMA.materia')),
            ],
            options={
                'unique_together': {('materia', 'maestro')},
            },
        ),
        migrations.CreateModel(
            name='UsuarioMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PEMA.materia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('materia', 'usuario')},
            },
        ),
        migrations.DeleteModel(
            name='MateriaUsuario',
        ),
    ]
