# Generated by Django 5.0.3 on 2024-06-06 03:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PEMA', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='_corresponsables',
            field=models.ManyToManyField(blank=True, related_name='corresponsables_carrito', to=settings.AUTH_USER_MODEL),
        ),
    ]
