# Generated by Django 5.0 on 2024-02-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PEMA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='codigo',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='articulo',
            unique_together={('nombre', 'codigo')},
        ),
    ]
