# Generated by Django 5.0.3 on 2024-06-06 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PEMA', '0002_alter_carrito__corresponsables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion',
            name='almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PEMA.almacen'),
        ),
    ]
