# Generated by Django 5.0.3 on 2024-06-10 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PEMA', '0003_alter_devolucion_almacen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorizacionorden',
            name='tipo',
            field=models.CharField(choices=[('OR', 'Ordinaria'), ('EX', 'Extraordinaria')], default='EX', max_length=2),
        ),
    ]
