# Generated by Django 5.0.3 on 2024-06-10 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PEMA', '0005_alter_autorizacionorden_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='lugar',
            field=models.CharField(choices=[('CA', 'En el Campus'), ('EX', 'Fuera del Campus')], default='EX', max_length=2, verbose_name='Lugar de la Producción'),
        ),
    ]
