# Generated by Django 5.0.3 on 2024-06-10 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PEMA', '0006_alter_carrito_lugar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorizacionorden',
            name='tipo',
            field=models.CharField(choices=[('OR', 'Ordinaria'), ('EX', 'Extraordinaria')], default='EX', max_length=2),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='lugar',
            field=models.CharField(choices=[('CA', 'En el Campus'), ('EX', 'Fuera del Campus')], default='CA', max_length=2, verbose_name='Lugar de la Producción'),
        ),
    ]
