# Generated by Django 5.0.3 on 2024-06-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PEMA', '0007_alter_autorizacionorden_tipo_alter_carrito_lugar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorizacionorden',
            name='tipo',
            field=models.CharField(choices=[('OR', 'Ordinaria'), ('EX', 'Extraordinaria')], default='OR', max_length=2),
        ),
    ]
